### ISSUE TITLE
module java.base does not open java.lang.reflect to module XR3Player

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#53]
When I start XR3Player (current master branch), I get the following written to the console, including error messages. I'm running in IntelliJ IDEA Community 2019.2.

Entered JavaFX Application Start Method
Path :-> /Users/helge/Documents/GitHub/XR3Player/target/classes/
Stream player Status -> NOT_SPECIFIED
Stream player Status -> NOT_SPECIFIED
Stream player Status -> NOT_SPECIFIED
java.lang.RuntimeException: **java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to module XR3Player**
	at XR3Player/com.goxr3plus.xr3player.application.MainLoader.makeNonFinal(MainLoader.java:428)
	at XR3Player/com.goxr3plus.xr3player.application.MainLoader.lambda$startPart2$9(MainLoader.java:358)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.IllegalAccessException: module java.base does not open java.lang.reflect to module XR3Player
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:206)
	at XR3Player/com.goxr3plus.xr3player.application.MainLoader.makeNonFinal(MainLoader.java:425)
	... 2 more
XR3Player ready to rock!

**Comment by goxr3plus** [comment]
Yeah it's because i am trying to use reflection yo overpass JxBrowser license like i did always but reflection doesn't work in Java 13 :'(

**Comment by goxr3plus** [comment]
@HelgeStenstrom  I literally don't know what to do with the Chromium Browser , they don't have anymore open source license for JxBrowser . It seems i will use my own library https://github.com/goxr3plus/JavaFX-Web-Browser again.

But it's very limited because its a JavaFX Browser not based on Chromium .... do you recommend me something ? It's like a big feature of XR3Player which is missing now due to that damn licenses they have.

**Comment by HelgeStenstrom** [comment]
I have no experience with that, and I don't know why a built in web-browser is needed in this application. Sorry.

**Comment by goxr3plus** [comment]
I am using JxBrowser so the user can navigate like he/she has Google Chrome inside XR3Player and i am using it in various things like dropbox authentication with XR3Player , download the latest version not from the repository but from here and have a look at the Browser :) 

https://goxr3plus.github.io/xr3player.io/

**Comment by JJBRT** [comment]
Please take a look at my new article that explain [how to export all modules to all modules at runtime in Java 16 and later](https://dev.to/jjbrt/how-to-avoid-resorting-to-add-exports-and-add-opens-in-jdk-16-and-later-j3m) without using any JVM parameter

**Comment by goxr3plus** [comment]
@JJBRT  Thanks mate :)
